### ISSUE TITLE
Extension use of target group "Zielgruppen"

### ISSUE THREAD

**Issue by rogerbaba** [BLC-FHGR/moodle-local_eventocoursecreation#20]
The data for target groups is not available over the evento webservice at the moment. 
So the implementation uses the course of study string in the category id to decide with courses belongs to this category to be created. Kurt Casutt said that we also could use the "Veranstalter" for this and the data should be correct entered with the right "Veranstalter".
now:
Marketing (dbm) HS18

improvement:
Marketing (dbm_vz_18, dbm_tz_18) HS18

so the assistant do not need to rename the course name anymore.

Todo:
-  extend the local_evento plugin to get the data from webservice
- extend option for naming like @ZG@
- implmenet naming for target groups

**Comment by zg** [comment]
Thanks for the highlight.
